config/routes.rb
Rails.application.routes.draw do
  comfy_route :cms_admin, :path => '/admin'
  get 'comfy/admin/cms/seos/index'
  get 'comfy/admin/cms/seos/check'
  get 'comfy/admin/cms/seos/wait'
  get 'comfy/admin/cms/seos/details'

  # Make sure this routeset is defined last
  comfy_route :cms, :path => '/', :sitemap => false
end

app/controllers/comfy/admin/cms/base_controller.rb
class Comfy::Admin::Cms::BaseController < ComfortableMexicanSofa.config.base_controller.to_s.constantize

  include Comfy::Paginate

  # Authentication module must have `authenticate` method
  include ComfortableMexicanSofa.config.admin_auth.to_s.constantize

  # Authorization module must have `authorize` method
  include ComfortableMexicanSofa.config.admin_authorization.to_s.constantize

  protect_from_forgery

  before_action :authenticate,
                :load_admin_site,
                :set_locale,
                :load_fixtures,
                :except => :jump

  layout 'comfy/admin/cms'

  if ComfortableMexicanSofa.config.admin_cache_sweeper.present?
    cache_sweeper *ComfortableMexicanSofa.config.admin_cache_sweeper
  end

  def jump
    path = ComfortableMexicanSofa.config.admin_route_redirect
    return redirect_to(path) unless path.blank?
    load_admin_site
    redirect_to comfy_admin_cms_site_pages_path(@site) if @site
  end

protected

  def load_admin_site
    if @site = ::Comfy::Cms::Site.find_by_id(params[:site_id] || session[:site_id]) || ::Comfy::Cms::Site.first
      session[:site_id] = @site.id
    else
      I18n.locale = ComfortableMexicanSofa.config.admin_locale || I18n.default_locale
      flash[:danger] = I18n.t('comfy.admin.cms.base.site_not_found')
      return redirect_to(new_comfy_admin_cms_site_path)
    end
  end
  
  def set_locale
    super
  rescue
    I18n.locale = cms_locale
  end

  def cms_locale
    ComfortableMexicanSofa.config.admin_locale || (@site && @site.locale)
  end

  def load_fixtures
    return unless ComfortableMexicanSofa.config.enable_fixtures

    controllers = %w(layouts pages snippets files).collect{|c| 'comfy/admin/cms/' + c}
    if controllers.member?(params[:controller]) && params[:action] == 'index'
      ComfortableMexicanSofa::Fixture::Importer.new(@site.identifier).import!
      flash.now[:danger] = I18n.t('comfy.admin.cms.base.fixtures_enabled')
    end
  end
end

app/controllers/comfy/admin/cms/seos_controller.rb
require 'seo_check'

class Comfy::Admin::Cms::SeosController < Comfy::Admin::Cms::BaseController
  def index
  end

  def wait
    render 'wait'
  end

  def check
    webpage = 'https://www.clark.de'
    crawler = Crawler.new(webpage)
    @result = crawler.crawl_webpage
  end
end

app/views/layouts/comfy/admin/cms/_left.html.haml
= render 'comfy/admin/cms/partials/navigation_before'

%ul.navigation
  %li= active_link_to t('comfy.admin.cms.base.sites'), comfy_admin_cms_sites_path, :active => ['comfy/admin/cms/sites']

  - if @site && !@site.new_record?
    %li= active_link_to t('comfy.admin.cms.base.layouts'), comfy_admin_cms_site_layouts_path(@site)
    %li= active_link_to t('comfy.admin.cms.base.pages'), comfy_admin_cms_site_pages_path(@site)
    %li= active_link_to t('comfy.admin.cms.base.snippets'), comfy_admin_cms_site_snippets_path(@site)
    %li
      - unless is_active_link?(comfy_admin_cms_site_files_path(@site))
        %a.cms-files-open-modal{:href => '#', :title => 'Open library'}
          %span.glyphicon.glyphicon-th-list
      = active_link_to t('comfy.admin.cms.base.files'), comfy_admin_cms_site_files_path(@site)
    %li= active_link_to t('comfy.admin.cms.base.seos'), comfy_admin_cms_seos_index_path


  = cms_hook :navigation

  = render 'comfy/admin/cms/partials/navigation_inner'

= render 'comfy/admin/cms/partials/navigation_after'