config/routes.rb
Rails.application.routes.draw do
  comfy_route :cms_admin, :path => '/admin'
  get 'comfy/admin/cms/seos/index'
  get 'comfy/admin/cms/seos/check'
  get 'comfy/admin/cms/seos/wait'
  get 'comfy/admin/cms/seos/details'

  # Make sure this routeset is defined last
  comfy_route :cms, :path => '/', :sitemap => false
end

app/controllers/comfy/admin/cms/base_controller.rb
class Comfy::Admin::Cms::BaseController < ComfortableMexicanSofa.config.base_controller.to_s.constantize

  include Comfy::Paginate

  # Authentication module must have `authenticate` method
  include ComfortableMexicanSofa.config.admin_auth.to_s.constantize

  # Authorization module must have `authorize` method
  include ComfortableMexicanSofa.config.admin_authorization.to_s.constantize

  protect_from_forgery

  before_action :authenticate,
                :load_admin_site,
                :set_locale,
                :load_fixtures,
                :except => :jump

  layout 'comfy/admin/cms'

  if ComfortableMexicanSofa.config.admin_cache_sweeper.present?
    cache_sweeper *ComfortableMexicanSofa.config.admin_cache_sweeper
  end

  def jump
    path = ComfortableMexicanSofa.config.admin_route_redirect
    return redirect_to(path) unless path.blank?
    load_admin_site
    redirect_to comfy_admin_cms_site_pages_path(@site) if @site
  end

protected

  def load_admin_site
    if @site = ::Comfy::Cms::Site.find_by_id(params[:site_id] || session[:site_id]) || ::Comfy::Cms::Site.first
      session[:site_id] = @site.id
    else
      I18n.locale = ComfortableMexicanSofa.config.admin_locale || I18n.default_locale
      flash[:danger] = I18n.t('comfy.admin.cms.base.site_not_found')
      return redirect_to(new_comfy_admin_cms_site_path)
    end
  end
  
  def set_locale
    super
  rescue
    I18n.locale = cms_locale
  end

  def cms_locale
    ComfortableMexicanSofa.config.admin_locale || (@site && @site.locale)
  end

  def load_fixtures
    return unless ComfortableMexicanSofa.config.enable_fixtures

    controllers = %w(layouts pages snippets files).collect{|c| 'comfy/admin/cms/' + c}
    if controllers.member?(params[:controller]) && params[:action] == 'index'
      ComfortableMexicanSofa::Fixture::Importer.new(@site.identifier).import!
      flash.now[:danger] = I18n.t('comfy.admin.cms.base.fixtures_enabled')
    end
  end
end

app/controllers/comfy/admin/cms/seos_controller.rb
require 'seo_check'

class Comfy::Admin::Cms::SeosController < Comfy::Admin::Cms::BaseController
  def index
  end

  def wait
    render 'wait'
  end

  def check
    webpage = 'https://www.clark.de'
    crawler = Crawler.new(webpage)
    @result = crawler.crawl_webpage
  end
end

app/views/comfy/admin/cms/seos/_error_feedback_array.html.haml
- if result.empty?
  %div No data, well done!
- else
  .url_show show/hide
  .url_show_content
    - result.each do |url|
      %div #{url.first}  [parent-> #{url.last}]

app/views/comfy/admin/cms/seos/_error_feedback_hash.html.haml
- if result.empty?
  %div No data, well done!
- else
  .url_show show/hide
  .url_show_content
    - result.each do |key, value|
      - if value.class.name == 'String'
        %div #{key}: #{value}
      - else
        %div #{key}: #{value.first} [parent-> #{value.last}]

app/views/comfy/admin/cms/seos/check.html.haml
%h1 Results
%h4 All valid urls with attributes:
- @result[:attributes_hash].each do |url, attributes|
  =link_to url, '', class: 'result_url'
  #result_attributes
    - attributes.each do |name, value|
      =link_to name, '', class: 'result_url_name'
      .result_url_value
        - if name == :image_and_alt
          - value.each do |src, alt|
            src= #{src} [alt= #{alt}]
            %br
        - elsif value.class.to_s == 'Hash'
          - value.each do |key, count|
            #{key} [count: #{count}]
            %br
        - elsif value.class.to_s == 'Array'
          - value.each do |link|
            #{link}
            %br
        - else
          #{value}
%h4 All system URLs:
=render partial: 'error_feedback_array', locals: {result: @result[:system_urls_array]}

%h4 All untested URLs:
=render partial: 'error_feedback_array', locals: {result: @result[:untested_urls_array]}

%h4 All error coded URLs:
=render partial: 'error_feedback_hash', locals: {result: @result[:error_urls_hash]}

%h4 Notes:
=render partial: 'error_feedback_hash', locals: {result: @result[:system_notes]}

app/views/comfy/admin/cms/seos/index.html.haml
%h1 SEO checklist
=link_to 'Check whole website', comfy_admin_cms_seos_wait_path
%table{:border => "1", :style => "width: 100%; border-collapse: collapse;"}
  %thead
    %tr
      %th content
      %th linking
      %th technical aspects
      %th user experience
  %tbody
    %tr
      /content
      %td
        %li content
        %li no duplicate content
        %li content formatting
        %li key pages are optimized
        %li all pages have titles, meta description, unique content
        %li amount of content versus ads
      /linking
      %td
        %li links
        %li devalue links
        %li links in content
        %li vertical linking structures are in place
        %li horizontal linking structures are in place
        %li breadcrump navigation
        %li use user sitemap
        %li proper navigation in footer
        %li redirects
        %li URLs are SEO friendly
      /technical aspects
      %td
        %li check robots.txt
        %li check sitemap.xml
        %li meta tags/data
        %li optimize page load
        %li optimize for different languages
        %li error tests
      /user experience
      %td
        %li optimized for different browsers and devices
        %li international optimized
        %li social media integration
        %li (navigation is easy)
        %li (webpage has Favicon and searching function)
        %li (every content is accessible with three clicks)

app/views/comfy/admin/cms/seos/wait.html.erb
<script>
  jQuery(document).ready(function() {
    window.location.replace('check')
  });
</script>

<h1>Please wait SEO check runs...</h1>
<img id="asdf-draggable-gif" src= <%= random_giphy %>>